### ISSUE TITLE
[help] How to install this on archlinux?

### ISSUE THREAD

**Issue by arun54321** [osleg/gebaar-libinput#12]
`[100%] Linking CXX executable gebaard
/usr/bin/ld: CMakeFiles/gebaard.dir/src/io/input.cpp.o: undefined reference to symbol 'udev_new@@LIBUDEV_183'
/usr/bin/ld: /usr/lib/libudev.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/gebaard.dir/build.make:144: gebaard] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/gebaard.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Error making: gebaar-libinput-git
`

I get this error too. 

```
Checking for one of the modules 'libinput'
-- Checking for module 'libudev'
--   Found libudev, version 244
-- Could NOT find UDEV (missing: UDEV_LIBRARY) 
-- Configuring done

```

**Comment by osleg** [comment]
Are you trying to build it manually or from AUR?

**Comment by arun54321** [comment]
From AUR.

**Comment by osleg** [comment]
It seems that something `udev`-related missing on your system. 
The only thing I can think of: 
Do you have `base-devel` pkg group installed? 
`pacman -Sy base-devel` might do the trick if you don't.

**Comment by arun54321** [comment]
Still it doesn't work. please see this. https://del.dog/unocorerig.go

**Comment by arun54321** [comment]
It compiles successfully after arch update.
