### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by 9ary** [osleg/gebaar-libinput#15]
The included libraries cpptoml and cxxopts fail to build on current Arch. Adding `#include <limits>` to both fixes it. Looks like cxxopts has been fixed, but gebaar is still using a very old version of it. cpptoml hasn't been updated in a long time so it may need patching.

**Comment by osleg** [comment]
Unfortunately I'm not using linux for last year and have no way to test/fix it :(

**Comment by 9ary** [comment]
Ah okay, would you like to hand over ownership of the AUR package to me?

**Comment by osleg** [comment]
Sure, I disowned bot gebaar-libinput-git and gebaar-libinput-fork

**Comment by 9ary** [comment]
Thanks! I've adopted both packages and I'll get them fixed ASAP.
