### ISSUE TITLE
Add debouncing

### ISSUE THREAD

**Issue by LiteracyFanatic** [osleg/gebaar-libinput#5]
I would like to control volume with vertical swipes and switch workspaces with horizontal swipes. Ideally I would like to do this with `swipe.settings.one_shot = false` since that seems more natural to me and mirrors the sort of gestures available on Windows. The issue is that the command will fire many times in rapid succesion as I swipe. This causes the volume to shoot up to 100% and my workspaces to rapidly toggle.  I think it would be good to have some sort of configurable pause before firing the command again: either waiting a fraction of a second or needing to swipe a minimum additional distance. That way you could have a single swipe but only increment the volume by 5% three times e.g. 

I've provided the libinput info for my touchpad as well as my `~/.config/gebaar/gebaard.toml` below.

```
Device:           SynPS/2 Synaptics TouchPad
Kernel:           /dev/input/event20
Group:            10
Seat:             seat0, default
Size:             117x57mm
Capabilities:     pointer gesture
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *two-finger edge 
Click methods:    *button-areas clickfinger 
Disable-w-typing: enabled
Accel profiles:   none
Rotation:         n/a
```

```
[swipe.commands.three]
up = "amixer set Master 5%+"
down = "amixer set Master 5%-"
left = "i3-msg workspace prev"
right = "i3-msg workspace next"

[swipe.settings]
threshold = 0.5
one_shot = false
trigger_on_release = false
```

**Comment by osleg** [comment]
Will look into that soon

**Comment by osleg** [comment]
Can you please test with #6, it should fix continuous swiping.

**Comment by LiteracyFanatic** [comment]
Awesome! It works correctly now. Thanks for the fix.
